apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: front-javascript
    version: v1
    project: {{ .Values.project | default "jump-app" }}
  name: front-javascript
spec:
  to:
    kind: Service
    name: front-javascript
  port:
    targetPort: http-8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: {{ .Values.route.security | default "Redirect" }}
  wildcardPolicy: None
